WebApp/Models/ErrorViewModel.cs
namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApp.BL.Auth;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ICurrentUser currentUser;

        public HomeController(ILogger<HomeController> logger, ICurrentUser currentUser)
        {
            _logger = logger;
            this.currentUser = currentUser;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net;
using WebApp.BL.Auth;
using WebApp.Middleware;
using WebApp.ViewMapper;
using WebApp.ViewModel;

namespace WebApp.Controllers
{
    [SiteNotAuthorize()]
    public class LoginController : Controller
    {
        private readonly IAuthBL authBL;
        public LoginController(IAuthBL authBL)
        {
            this.authBL = authBL;
        }

        [HttpGet]
        [Route("/login")]
        public IActionResult Index()
        {
            return View("Index", new LoginViewModel());
        }

        [HttpPost]
        [Route("/login")]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> IndexSave(LoginViewModel model)
        {
            try
            {
                await authBL.Authenticate(model.Email!, model.Password!, model.RememberMe == true);
                return Redirect("/");
            }
            catch (BL.Exceptions.AuthorizationException)
            {
                ModelState.AddModelError("Email", "Имя или Email не найден");
            }

            return View("Index", model);
        }
    }
}

WebApp/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Middleware;
using WebApp.ViewModel;
using WebApp.Service;
using WebApp.BL.Auth;
using WebApp.BL.Profile;
using WebApp.ViewMapper;
using WebApp.DAL.Models;

namespace WebApp.Controllers
{
    [SiteAuthorize()]
    public class ProfileController : Controller
    {
        public readonly ICurrentUser currentUser;
        public readonly IProfileBL profileBL;
        public ProfileController(ICurrentUser currentUser, IProfileBL profileBL)
        {
            this.profileBL = profileBL;
            this.currentUser = currentUser;
        }
        [HttpGet]
        [Route("/profile")]
        public async Task<IActionResult> Index()
        {
            var profiles = await currentUser.GetProfiles();

            ProfileModel? profileModel = profiles.FirstOrDefault();

            return View(profileModel != null ? ProfileMapper.MapProfileModelToProfileViewModel(profileModel) : new ProfileViewModel());
        }

        [HttpPost]
        [Route("/profile")]
        [AutoValidateAntiforgeryToken]
        public async  Task<IActionResult> IndexSave(ProfileViewModel model)
        {
            int? userId = await currentUser.GetCurrentUserId();
            if (userId == null) throw new Exception("Пользователь не найден");
            var profiles = await profileBL.Get((int)userId);
            if (model.ProfileId!=null && !profiles.Any(m => m.ProfileId == model.ProfileId))
                throw new Exception("Error");


            if (ModelState.IsValid)
            {
                ProfileModel profileModel = ProfileMapper.MapProfileViewModelToProfileModel(model);
                profileModel.UserId = (int)userId;
                if (Request.Form.Files.Count > 0 && Request.Form.Files[0] != null)
                {
                    WebFile webFile = new WebFile();
                    string fileName = webFile.GetWebFileName(Request.Form.Files[0].FileName);
                    await webFile.UploadAndResizeImage(Request.Form.Files[0].OpenReadStream(), fileName, 800, 600);
                    profileModel.ProfileImage = fileName;
                }
                await profileBL.AddOrUpdate(profileModel);
                return Redirect("/");
            }

            return View("Index", new ProfileViewModel());
        }
    }
}

WebApp/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.BL.Auth;
using WebApp.BL.Exceptions;
using WebApp.Middleware;
using WebApp.ViewMapper;
using WebApp.ViewModel;

namespace WebApp.Controllers
{
    [SiteNotAuthorize()]
    public class RegisterController:Controller
    {
        private readonly IAuthBL authBL;
        public RegisterController(IAuthBL authBL) 
        {
            this.authBL = authBL;
        }

        [HttpGet]
        [Route("/register")]
        public IActionResult Index()
        {
            return View("Index",new RegistrationViewModel());
        }

        [HttpPost]
        [Route("/register")]
        public async Task<IActionResult> IndexSave(RegistrationViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await authBL.Register(AuthMapper.MapRegistrationViewModelToUserModel(model));
                    return Redirect("/");
                }
                catch (DuplicateEmailException)
                {
                    ModelState.TryAddModelError("Email","Email уже существует");
                }
            }
            return View("Index", model);
        }
    }
}

WebApp/ViewComponents/MainMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.BL.Auth;

namespace WebApp.ViewComponents
{
    public class MainMenuViewComponent : ViewComponent
    {
        private readonly ICurrentUser currentUser;
        public MainMenuViewComponent(ICurrentUser currentUser) 
        {
            this.currentUser = currentUser;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            bool isLoggedIn = await currentUser.IsLoggedIn();
            return View("Index", isLoggedIn);
        }
    }
}

WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

WebApp/Views/Login/Index.cshtml
@model LoginViewModel


@{
    ViewData["Title"] = "Login";
}

<div>
    <form action="/login" method="post">
        @Html.AntiForgeryToken()
        <p>
            <label>Email</label>
            <input name="Email" type="email"/>
            <div class="error">@Html.ValidationMessageFor(m => m.Email)</div>
        </p>
        <p>
            <label>Password</label>
            <input name="Password" type="password" />
            <div class="error">@Html.ValidationMessageFor(m => m.Password)</div>
        </p>
        <p>
            <input name="RememberMe" type="checkbox" value="true" /> Remember Me
        </p>
        <button>Login</button>
    </form>
</div>

WebApp/Views/Register/Index.cshtml
@model RegistrationViewModel


@{
    ViewData["Title"] = "Registration";
}

<div>
    <form action="/register" method="post">
        <p>
            <label>Email</label>
            <input name="Email" type="email" value="@Model.Email"/>
            <div class="error">@Html.ValidationMessageFor(m => m.Email)</div>
        </p>
        <p>
            <label>Password</label>
            <input name="Password" type="password" />
            <div class="error">@Html.ValidationMessageFor(m => m.Password)</div>
        </p>
        <button>Register</button>
    </form>
</div>

WebApp/Views/Shared/Components/MainMenu/index.cshtml
@model bool
@if(Model){
    <li class="nav-item">
        <a class="nav-link text-dark" href="/profile">Порофиль</a>
    </li>
}
else{
    <li class="nav-item">
        <a class="nav-link text-dark" href="/login">Войти</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" href="/register">Зарегистрироваться</a>
    </li>
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Home/Privacy">Privacy</a>
                        </li>
                        @await Component.InvokeAsync("MainMenu")
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>